version: '3'
services:
  db:
    image: 'postgres:11'
    container_name: 'user-service-ktor'
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=UserDB
volumes:
  database:
